export const primaryColor: string = '#FFA500'
export const backgroundColor1: string = '#502FA3'
export const backgroundColor2: string = '#019CAD'
export const darkGrey: string = '#343A40'
export const footerBackgroundColor: string = '#222222'
